name: Test

on:
  push:
    branches:
      - master
      - test

jobs:
  check:
    name: Json format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: cat ./test-data.txt


  deployment:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: cat ./test-data.txt
      - name: Task1-compare
        run: echo ${{ secrets.TEST_S }}

  call-reusable-workflows:
    uses: ./.github/workflows/reuseable-workflow.yml
    with:
      ENVIRONMENT: te
    secrets:
      TEST_S: ${{ secrets.TEST_S }}
